name: gobi-insert-stories
version: 3.0.1
description: Lets you click to pop up Gobi bubbles on any webpage
main: src/index.coffee
scripts:
  create-zip: zip -r ../GobiInsertStories.zip . -x '*.git*' -x '*node_modules*'
  build: sh build.sh
  test: jest
dependencies: {}
devDependencies:
  coffeescript: ^2.2.3
  jest: ^25.1.0
  jest-preset-coffeescript: ^1.1.1
  pug: ^2.0.4
  stylus: ^0.54.7
  jstransformer-stylus: ^1.5.0
jest:
  verbose: true
  preset: jest-preset-coffeescript
  testRegex: tests/.*jest\.coffee
  moduleFileExtensions:
    - coffee
    - js
    - ts
    - json
repository:
  type: git
  url: git+https://github.com/ovikholt/GobiInsertStories.git
keywords:
  - gobi
  - story
  - stories
  - bubbles
author: ovikholt@gmail.com
license: UNLICENSED
bugs:
  url: https://github.com/ovikholt/GobiInsertStories/issues
homepage: https://github.com/ovikholt/GobiInsertStories#readme
